services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: app-backend
    ports:
      - "18080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: app-frontend
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE: "http://novikovn383.fvds.ru:18080"
      NITRO_HOST: "0.0.0.0"
      NITRO_PORT: "3000"
    depends_on:
      - backend
    restart: unless-stopped